### ISSUE TITLE
User Story # 17 - Articles feature setup 

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido_v2#1]
As an **admin**, I want to be able to **manage article posting admin** so that I can **maintain the websites features.**

**Acceptance Criteria**
- An admin user can manage the posting of articles, drafts and approval of comments.

**Tasks**

- [x] Create Articles app
- [x] Connect urls/views/templates
- [x] Connect user with article ownership
- [x] Add 'articles' to INSTALLED APPS
- [x] Configure admin.py for admin access
