### ISSUE TITLE
User Story # 25 - Create an Article

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido_v2#10]
As a **user**, I can **fill-in, edit and save an article text field** so that I can **create and share an article from my profile**.

**Acceptance Crteria**
1. User can navigate to the the 'Add Article' page.
2. Django RichTextField is visible to user to enter and edit their article.
3. 'Save&Post' button allows the user to save the article and share it to the Article view page.

**Tasks**

- [x] Install and setup Django RichTextField editor
- [x] Make changes to models.py and migrate
- [x] Create 'add_article.html' page
- [x] Create method to navigate to 'add_article' page, enter the article data and save it to the user's model profile and to the article page. 
- [x] Ensure authentication is present and that the article saves to the user's model database

**Comment by amylour** [comment]
- Possible bug with slug not populated with title field
