### ISSUE TITLE
User Story # 27 - Edit Article

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido_v2#13]
As a **user** I can **click on the edit button of my article** so that I can **edit the article and save it again**.

**Acceptance Criteria**
1. Successful access to edit button for registered owner of the article
2. Edit button redirects user to the edit article page
3. Edit form data saves and article is reposted with the new information

**Tasks**

- [x] Create 'Edit Article' html.
- [x] Create edit view using Django UpdateView functionality
- [x] Link urls to relevant buttons.
- [x] Test edit button to ensure only for registered users and that it is changing the data when saved.

**Comment by amylour** [comment]
- Investigate whether edited post needs to be approved again by the admin.
