### ISSUE TITLE
User Story # 28 - Search function

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido_v2#15]
As a **user**, I can **enter a search term into the search bar** so that I can **search for particular articles and articles with information topics that I am interested in**.

**Acceptance Criteria**
1. User can see the 'search' bar in the navbar of the Article page views only
2. Search bar takes user input
3. Article page displays search results

**Tasks**

- [x] Create search bar html
- [x] Create Search bars function in views.py
- [x] Search bar only yields 'published' articles
- [x] Check returned article is viewable when clicked
