### ISSUE TITLE
User Story # 29 - Delete comment

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido_v2#16]
As a **user**, I can **click a delete button** so that I **can remove a comment that I have made**.

**Acceptance Criteria**

1. User can see the 'delete' button for removing comment.
2. User is brought to confirm comment deletion page.
3. Comment is removed successfully.

**Tasks**

- [x] Add 'delete' button to comment area for registered user's related comment
- [x] Delete button brings user to confirm deletion page
- [x] Confirm deletion page created
- [x] Comment is removed and redirect back to article page
