### ISSUE TITLE
User Story # 30 - User Feedback for max booking allowance

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido_v2#17]
As a **user**, I can **get feedback from the website** that will **explain that only four active bookings are allowed per person**.

**Acceptance Criteria**
1. User is informed via message that they cannot have more than 4 active bookings.
2. User is unable to book more than 4 bookings per account.

**Tasks**

- [x] Create views.py code preventing the user from having more than 4 active bookings
- [x] Ensure message is displayed on screen when tested
- [x] Display User's active bookings in their profile
