### ISSUE TITLE
User Story # 31 - Upload image to Gallery Wall

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido_v2#18]
As a **user** I can **click the upload image button on the Gallery page** so that I can **upload an image of my dog have fun in the park**.

**Acceptance Criteria**
1. Upload image button brings user to upload image page
2. User can choose an image and give it a title and an image alt
3. Image is successfully uploaded to the Gallery page

**Tasks**

- [x] Create upload image form
- [x] Write upload image views
- [x] Connect the urls
- [x] Test that image is saved correctly to Cloudinary via admin panel and displayed on page
