### ISSUE TITLE
Dev Task # 14 - Home Page: Style & Content

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido_v2#20]
As a **developer**, I can **add content and styling to my home page** so that **it is informative and engaging for the user**.

**Acceptance Criteria**
1. User is engaged with the website's styling
2. Website meets accessibility standards for contrast
3. Information is clear
4. Images are rendered appropriately 

**Tasks**

- [x] Add logo and icons to navbar
- [x] Tidy hero section -> add 'Book Now' button
- [x] Add About/Safety/Benefits text + images
