### ISSUE TITLE
Dev Task # 19 - Visit Us Page: Styling & Content

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido_v2#24]
As a **developer** I can **add content and styling to my visit us page** so that it can **inform and guide a park visitor**.

**Acceptance Criteria**
1. Visit Us page shows map of park location
2. Park address and Opening Times clearly displayed
3. User reviews are displayed

**Tasks**

- [x] Add CSS and Bootstrap styling to page
- [x] Connect Google Map to the page for interactivity
- [ ] Create User Review feature

**Comment by amylour** [comment]
- User Review feature is a 'Could Have' as per MosCoW principle and as such is not included with this MVP sprint
