### ISSUE TITLE
Dev Task # 17 - Gallery Page: Styling & Content

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido_v2#26]
As a **developer** I can **add styling to the Gallery page** so that it has **a successful UX/UI**.

**Acceptance Criteria**
1. Add photo icon works
2. Design fits in with wireframes
3. Ensure photos added add to the layout correctly
4. Delete image button is visible and works

**Tasks**

- [x] Create add photo icon
- [x] Change Gallery forms to fit in with color scheme
- [x] Position delete photo button for relevant authenticated user
