### ISSUE TITLE
User Story # 19 - View Likes

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido_v2#3]
As a **user**, I would like to **view an article's likes** so that I can **find the most interesting articles**.

**Acceptance Criteria**
- Successful addition of like icon under article post

**Tasks**

- [x] Source 'like' icon
- [x] Add icon to static/icons
- [x] Add icon img tag to article.html
