### ISSUE TITLE
Dev Task # 21 - README.md updating

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido_v2#30]
As a developer I can **create and update a README.md file** so that I can **record and document my project progress**.

**Tasks**

- [x] Create README.md
- [x] Create README structure and contents
- [x] Complete README sections with project info
- [x] Screenshot wireframes/features/design content for addition to README
- [x] Add Deployment section
- [x] Update Credits section with reading material and tutorials
- [x] Spell check and format
