### ISSUE TITLE
Dev Task # 22 TESTING.md create and update

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido_v2#31]
As a developer I can **create and update a TESTING.md file** so that I can **record and document the testing of my project**.

**Tasks**

- [x] Create a TESTING.md file
- [x] Create structure of TESTING file
- [x] Update TESTING sections 
- [x] Add screenshots of testing validation/bugs/form validation
- [x] Spellcheck and format
