### ISSUE TITLE
Testing #1 - Home Page

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido_v2#32]
As a **developer** I can **thoroughly test my Home Page** so that I can **ensure that there are no bugs or issues left for the user**.

**Acceptance Criteria**
- Home Page is fully responsive, cross-browser compatible, runs without any bugs

**Tasks**

- [x] Check responsiveness
- [x] Test all buttons/forms/inputs
- [x] Test across browsers
- [x] Validate HTML
- [x] Validate JavaScript
- [x] Validate Python
- [x] Record results in TESTING.md
