### ISSUE TITLE
Testing #2 - SignIn/SignUp

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido_v2#34]
As a **developer** I can **thoroughly test my Sign In/SignUp pages** so that I can **ensure that there are no bugs or issues left for the user**.

**Acceptance Criteria**
- Sign Up/In pages are fully responsive, cross-browser compatible, run without any bugs

**Tasks**

- [x] Check responsiveness
- [x] Test all buttons/forms/inputs
- [x] Test across browsers
- [x] Validate HTML
- [x] Validate JavaScript
- [x] Validate Python
- [x] Record results in TESTING.md
