### ISSUE TITLE
User Story # 20 - View Articles

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido_v2#4]
As a **user** I can **visit the articles page** so that I **can read and interact with the articles**.

**Acceptance Criteria**
- User can access the 'Articles' page via the navbar.
- Articles page displays article cards for user to choose.

**Tasks**

- [x] Create Articles template page
- [x] Connect views and urls
- [x] Update navbar link to bring user to Articles page
- [x] Basic styling of page
