### ISSUE TITLE
Testing #4 - Articles Feature

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido_v2#42]
As a **developer** I can **thoroughly test my Article Feature** so that I can **ensure that there are no bugs or issues left for the user**.

**Acceptance Criteria**
- Article Feature is fully responsive, cross-browser compatible, runs without any bugs

**Tasks**

- [x] Check responsiveness
- [x] Test all buttons/forms/inputs
- [x] Test across browsers
- [x] Validate HTML
- [x] Validate JavaScript (if applicable)
- [x] Validate Python
- [x] Record results in TESTING.md
