### ISSUE TITLE
Dev Task - Project Planning Setup

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido_v2#45]
As a **developer**, I can **set up my project planning environments** so that I can ** drive my project forward and keep track of my projects progress**.

**Tasks**

- [ ] Set up GitHub Projects board
- [ ] Set up Project 5 local folder
- [ ] Set up Figma file for wireframes
- [ ] Setup Lucidchart for ERD
