### ISSUE TITLE
User Story # 23 - Comment on a post

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido_v2#6]
As a **user** I can **comment on a post** so that I can **interact and get involved with the conversation**.

**Acceptance Criteria**
- A text field and submit button allows an authenticated user to submit a comment.

**Tasks**

- [x] Create comment field on article page html
- [x] Ensure user is authenticated so that they can interact with the comment field
- [x] Connect user model with the article post model and comment model
