### ISSUE TITLE
User Story # 22 - Like/Unlike Article

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido_v2#7]
As a **user** I can **click a button icon** so that I **can like/unlike and article**.

**Acceptance Criteria**
- Button Icon allows user interaction with the article

**Tasks**

- [x] Create button icon link
- [x] Ensure user authentication for button interaction
- [x] Connect like button with user model
