### ISSUE TITLE
User Story # 24 - Alert messages

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido_v2#8]
As a **user** I want **to see a message when I have successfully/unsuccessfully completed an action** so that I can **receive feedback from my interaction with the website**.

**Acceptance Criteria**
1. Alert message displays successfully for login/logout/errors/information.
2. Alert message disappears by itself after a set amount of time and have a manual close button.
3. Alert messages styled to reflect the project whilst staying sensitive to the alert type.

**Tasks**

- [x] Create alert message HTML using Bootstrap
- [x] Add new classes to add my own styling for the project design
- [x] Add JS setTimeout function to have the message fade away after a set amount of time.
- [x] Add additional message to inform user if their comment has been approved and posted.
