### ISSUE TITLE
User Story # 24 - Gallery page

### ISSUE THREAD

**Issue by amylour** [amylour/FreeFido_v2#9]
As a **user**, I can **visit the gallery page** so that I can **view the gallery wall of photos**.

**Acceptance Criteria**
1. User can visit the gallery page when clicking on the gallery link.
2. Gallery page is viewable by registered and non-registered users.

**Tasks**

- [x] Create basic gallery page
- [x] Link urls and navbar button
- [x] Write view for gallery view page
